### PR TITLE
Update Ubuntu brand colour

### PR DESCRIPTION
**Pull request by anthonydillon**
Ubuntu's brand colour changed from #DD4814 to #E95420. This can be found on the Ubuntu design sites colour palette:
https://design.ubuntu.com/brand/colour-palette

### CODE REVIEW

**Comment by donroyco** [comment]
You should not update the `index.html` file directly, but update the `src/simple-icons.json` with the color.

**Comment by anthonydillon** [comment]
Thanks, @donroyco I have replaced all instances now.

**Comment by danleech** [comment]
Hi, @anthonydillon. Sorry, this PR was closed automatically because I deleted the `gh-pages` branch. Would you mind making another PR to the `develop` branch, by adding the new colour to `_data/simple-icons.json`? Cheers!

**Comment by anthonydillon** [comment]
No problem @danleech. PR ready https://github.com/danleech/simple-icons/pull/419.

**Pull request closed without merging**
