### PR TITLE
Adding GNU, Mozilla, Linux, Intel logos

### PR DESCRIPTION
**Pull request by rosslh**

### CODE REVIEW

**Comment by rosslh** [comment]
^ fixed linux logo

**Comment by rosslh** [comment]
@danleech could this be merged please?

**Comment by rosslh** [comment]
Any reason this wasn't merged @danleech? Happy to fix any issues.

**Comment by danleech** [comment]
Hi, @rosslh. Sorry, this PR and others were closed when I deleted the `gh-pages` branch earlier this week. I haven’t had a chance to write up new contributing instructions yet, and haven’t reached out to contributors whose PRs were closed.

If you want to resubmit these changes to the `develop` branch I can merge them in. Note that `simple-icons.json` has moved to the `_data` directory, so that Jekyll can build pages automatically.

**Pull request closed without merging**
