### PR TITLE
Add Sogou, Salesforce, Yandex, Pluralsight, NPM, Redux, Gerrit, AngelList, NGINX, Signal, Keep, Atom, Sublime, Visual Studio Code, WebStorm, Keybase, Pandora, Strava, SourceForge, SlickPic and AIM

### LINKED ISSUE #460: Request: SOGOU
via https://twitter.com/zuojj/status/867986912857817089

https://www.sogou.com/

### PR DESCRIPTION
**Pull request by birjolaxew**
Each commit has comments explaining various decisions for it.

Fixes #460, #455, #449, #450, #444, #441, #442, #452, #413, #393, #374, #351, #343, #230, #193, #138 and #421.

### CODE REVIEW

**Comment by birjolaxew** [comment]
That's prolly going to be all from me this time. If any changes are needed, just leave a comment.

**Comment by greybax** [comment]
Any issues to push these changes in master branch?

**Comment by birjolaxew** [comment]
I'm fairly sure @danleech simply isn't really up for the task of maintaining a semi-popular repo. If ready-to-go pull requests are allowed to go a month without as much as a comment, that just kind of scares away contributors.

**Comment by greybax** [comment]
Meanwhile I'm ready to maintain this repo. If I'll get to write access to this repo I can to monitor PRs. So I can see as one of solution @danleech can create an organization with this repo and add contributors to it for more quick PR reviews.

**Comment by greybax** [comment]
I've merged these changes into https://github.com/simple-icons/simple-icons @danleech please take a look and approve this changes. Also I've sent you request with owner access to [this org](https://github.com/simple-icons).

**Pull request merged**
