### PR TITLE
Add Schema.org

### PR DESCRIPTION
**Pull request by BesrourMS**

### CODE REVIEW

**Comment by danleech** [comment]
What’s this for?

**Comment by BesrourMS** [comment]
Include Your Site Name in Search Results : 
https://developers.google.com/structured-data/site-name#site_name_requirements

**Comment by kylewm** [comment]
Does schema have an icon?

**Comment by BesrourMS** [comment]
No : https://schema.org/

**Comment by kylewm** [comment]
Lol sorry, I misinterpreted, thought you were saying add a schema.org icon.

**Pull request closed without merging**
