### PR TITLE
Updated medium icon

### PR DESCRIPTION
**Pull request by pablocaro**
Hey there, Dan!

I am a designer at Medium - Thanks for adding our logo to simple-icons!. This is our one color version - We'd love if you update it :) - have a great day!

### CODE REVIEW

**Comment by danleech** [comment]
@pablocaro Fantastic! Thank you. I saw this variant in the Medium post about the logo’s development, but couldn’t find a vector version of it anywhere.

**Comment by tylerhowarth** [comment]
@danleech updated brand guidelines are on the way - we'll update the `simple-icons.js` file once we've posted them.

**Comment by pablocaro** [comment]
Awesome! Thanks @danleech !

**Comment by danleech** [comment]
@tylerhowarth @pablocaro Thanks again, chaps. 👍

**Pull request merged**
