### PR TITLE
Add ProcessWire icon

### PR DESCRIPTION
**Pull request by adrianbj**
ProcessWire is an API driven PHP CMF/CMS.

https://processwire.com

Thanks for considering this addition!

### CODE REVIEW

**Comment by AndZyk** [comment]
👍

**Comment by outflux3** [comment]
👍

**Comment by ocorreiododiogo** [comment]
👍

**Comment by horst-n** [comment]
+1

**Comment by adrianbj** [comment]
Thanks @danleech - much appreciated!

**Comment by danleech** [comment]
@adrianbj Thank _you_!

**Pull request merged**
